# Generated by Django 3.1.7 on 2021-08-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fieldscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.TextField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('date', models.DateField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('companion1', models.TextField(default=0)),
                ('companion2', models.TextField(default=0)),
                ('companion3', models.TextField(default=0)),
            ],
        ),
    ]
