# Generated by Django 3.1.7 on 2021-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amsales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('sales_plan', models.FloatField(default=0)),
                ('sales', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('korea_value', models.FloatField(default=0.0)),
                ('china_value', models.FloatField(default=0.0)),
                ('global_value', models.FloatField(default=0.0)),
                ('goal_value', models.FloatField(default=0.0)),
                ('sales_month_plan', models.FloatField(default=0.0)),
                ('sales_month', models.FloatField(default=0.0)),
                ('am_sales_month_plan', models.FloatField(default=0.0)),
                ('am_sales_month', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('sales', models.FloatField(default=0)),
                ('before6_sales', models.FloatField(default=0)),
                ('after6_sales', models.FloatField(default=0)),
                ('machines', models.IntegerField(default=0)),
                ('stocks', models.FloatField(default=0.0)),
                ('korea_free_material', models.FloatField(default=0.0)),
                ('global_free_material', models.FloatField(default=0.0)),
                ('free_retrofit', models.FloatField(default=0.0)),
            ],
        ),
    ]
