# Generated by Django 3.1.7 on 2021-07-23 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Location')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('parscore1', models.SmallIntegerField(default=3)),
                ('parscore2', models.SmallIntegerField(default=3)),
                ('parscore3', models.SmallIntegerField(default=3)),
                ('parscore4', models.SmallIntegerField(default=3)),
                ('parscore5', models.SmallIntegerField(default=3)),
                ('parscore6', models.SmallIntegerField(default=3)),
                ('parscore7', models.SmallIntegerField(default=3)),
                ('parscore8', models.SmallIntegerField(default=3)),
                ('parscore9', models.SmallIntegerField(default=3)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scard.club')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('myscore1', models.SmallIntegerField(default=3)),
                ('myscore2', models.SmallIntegerField(default=3)),
                ('myscore3', models.SmallIntegerField(default=3)),
                ('myscore4', models.SmallIntegerField(default=3)),
                ('myscore5', models.SmallIntegerField(default=3)),
                ('myscore6', models.SmallIntegerField(default=3)),
                ('myscore7', models.SmallIntegerField(default=3)),
                ('myscore8', models.SmallIntegerField(default=3)),
                ('myscore9', models.SmallIntegerField(default=3)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scard.club')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scard.course')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
            options={
                'ordering': ('owner',),
            },
        ),
    ]
