# Generated by Django 3.1.7 on 2021-08-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
